export const INCREMENT_COUNTER_1 = 'INCREMENT_COUNTER_1';
export const INCREMENT_COUNTER_2 = 'INCREMENT_COUNTER_2';
export const SET_COUNTER_VALUE_1 = 'SET_COUNTER_VALUE_1';
export const SET_COUNTER_VALUE_2 = 'SET_COUNTER_VALUE_2';